<CustomTextInput@TextInput>
    input_filter: 'float'
    input_type: 'number'
    halign: 'center'
    padding: 0
    multiline: False
    write_tab: False
    font_size: '30sp'
    font_name: 'assets/fonts/Poppins-Bold.ttf'
    cursor_width: '2sp'
    background_color: 1, 1, 1, 0
    cursor_color: '#ffffff'
    foreground_color: '#ffffff'
    pos_hint: {'center_x':.5, 'center_y':.5}
    size_hint: 1, None
    height: self.minimum_height